facebook:
    client:
      clientId: 1025933537747585
      clientSecret: 5a18bf1e751a45b96aec54b31398edf3
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

google:
    client:
      clientId: 792472175593-sqffupr4pd9q3vpc63q3mihbn1dq2dbr.apps.googleusercontent.com
      clientSecret: U9LkmCfh4aDTQ_w66NkyMtzh
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: openid,email,profile

    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true